name: Built with Eleventy
description: Show off your Eleventy site on the Eleventy documentation
labels: built-with-eleventy
body:
  - type: input
    id: url
    attributes:
      label: Site URL
      description: The home page of the live web site you built
      placeholder: e.g. https://www.zachleat.com/
    validations:
      required: true
  - type: markdown
    value: |
      We will spider your site to look for:
      * a `<a href rel="source">` that links to the URL for the source code for this site (if open source).
