name: Built with Eleventy
description: Show off your Eleventy site on the Eleventy documentation
labels: built-with-eleventy
body:
  - type: input
    id: url
    attributes:
      label: Site URL
      description: The home page of the live web site you built
      placeholder: e.g. https://www.zachleat.com/
    validations:
      required: true
  - type: input
    id: url-source
    attributes:
      label: Source code URL
      description: URL to the source code for this site (if open source)
      placeholder: e.g. https://github.com/zachleat/zachleat.com
    validations:
      required: false
